### ISSUE TITLE
DataManager is DataCache - rename probably?

### ISSUE THREAD

**Issue by nchursin** [testmyorgdotcom/testmyorg#6]
I'm working on redoing DataManager in TS and it seems like it's more a cache than some kind of manager. Also, probably it makes sense to move `ensure` method to a decorator or sth... Thoughts?

A use case for another decorator - I want to search for records in both cache and Salesforce

**Comment by baksale** [comment]
All data created with the help of the Test Framework will end up in TestDataManager.

I'm not good at decorators, need an example.

Need to hide methods: constructSObject method.

**Comment by nchursin** [comment]
I'd suggest splitting this into `Cache` (or `Storage`) and `Ensurer` or whatever we should call it. 

`Cache` is a singleton providing an API to store and search. `Ensurer` provides decoration for search, that creates a record in Salesforce and stores the result. This way we make it more flexible. E.g. you can ensure under different users, but still use the same cache
