### ISSUE TITLE
Encapsulate cached data completely

### ISSUE THREAD

**Issue by nchursin** [testmyorgdotcom/testmyorg#7]
Currently, data in the cache is exposed via a getter. Since this is completely internal information for the manager, should we make it private? Or at least package-private?

**Comment by baksale** [comment]
It is possible if we expose
void/DeleteResults[] cleanMethod(Function<Id[],DeleteResults[]> deleter/SalesforceDataAction);

**Comment by nchursin** [comment]
Sounds good
